repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest version
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest version
    hooks:
      - id: flake8